config/routes.rb
Rails.application.routes.draw do
  resources :posts
  devise_for :accounts
  #devise_for :users 
  #root "articles#index"
  #get "/articles", to: "articles#index"

  get "/browse" => "browse#browse", as: :browse

  root to: "posts#index"
  get "/index" => "posts#index", as: :index

  # get "/post" => "#post", as: :home



end

app/models/account.rb
class Account < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_devise, if: :devise_controller?

    private

    def configure_devise
        devise_parameter_sanitizer.permit(:account_update, keys: [ :lolname ])
    end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
  end
end

app/controllers/browse_controller.rb
class BrowseController < ApplicationController

    def browse
        @users = Account.where.not(id: current_account.id)
    end
    
    def approve
        
    end
    
    def decline
        
    end
    
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:name, :surname, :discord, :Pseudo, :game, :others, :image)
    end
end

app/controllers/public_controller.rb
class PublicController < ApplicationController

    def home
        
    end
    

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/browse/browse.html.erb
<div class="slides-container">
    <div id="slides">
        <% @users.each_with_index do |user, i|  %>
        <div class="slide" <%= 'showing' if i == 0 %> data-id="<%= user.id %>">
            <div class="user-details">
                <span class="user-name"><%= user.lolname %></span>, S2 <br />

            </div>
        </div>
        <% end %>
    </div>
    <div id="slide-controls">
        <span id="decline"><i class="fa fa-times-circle fa-2x"></i></span>
        <span id="approve"><i class="fa fa-praying-hands fa-2x"></i></span>
    </div>
</div>

app/views/layouts/_footer.html.erb
    <footer class="bg-dark text-center text-white">
      <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
      © 2020 Copyright:
      <a class="text-white" href="http://MeetMate.com/">MeetMate.com</a>
      </div>
    </footer>

app/views/layouts/_nav.html.erb
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
  <h5 class="my-0 mr-md-auto font-weight-normal navbar-brand" href="/#">Meet a Mate</h5>
  

  
  <% if account_signed_in? %>
    <nav class="my-2 my-md-0 mr-md-3">
      <%# <%= link_to "Browse", browse_path, class: "text-dark nr-3" %>
      <%= link_to "Accueil", index_path , class: "text-dark mr-3" %>
      <%= link_to "Settings",edit_account_registration_path, class: "text-dark" %>
    </nav>

  <%= link_to "Sign out", destroy_account_session_path(), method: :delete, class: "btn btn-secondary nr-2" %>  
  
  <% else %>
    <nav class="my-2 my-md-0 mr-md-3">
      <%# <a class="p-2 text-dark" href="#">Features</a> %>
      <%# <a class="p-2 text-dark" href="#">Support</a>
      <a class="p-2 text-dark" href="#">Pricing</a> %>
    
  <form class="input-group">
    <%= link_to "Sign in", new_account_session_path, class: "btn btn-secondary nr-2" %>
    <%= link_to "Sign up", new_account_registration_path, class: "btn btn-outline-primary" %>
  </form>
  </nav>


  
  <% end %>
  
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MeetMate</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="icon" type="image/png" href="https://media.discordapp.net/attachments/424556759013916672/840155908378066945/icon.png">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous">
  </head>

<body>
    <%= render 'layouts/nav' %>
    <div class="container">

      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-p34f1UUtsS3wqzfto5wAAmdvj+osOnFyQFpp4Ua3gs/ZVWx6oOypYoCJhGGScy+8" crossorigin="anonymous"></script>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :surname %>
    <%= form.text_field :surname %>
  </div>

  <div class="field">
    <%= form.label :discord %>
    <%= form.text_field :discord %>
  </div>

  <div class="field">
    <%= form.label :Pseudo %>
    <%= form.text_field :Pseudo %>
  </div>

  <div class="field">
    <%= form.label :game %>
    <%= form.text_field :game %>
  </div>

  <div class="field">
    <%= form.label :others %>
    <%= form.text_area :others %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.text_area :image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>

<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Supprimer', @post, class: "btn btn-lg btn-sm btn-danger",method: :delete, data: { confirm: 'Are you sure?' } %>
<br>
<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<% if account_signed_in? %>
 <div class="container">


   <div class="card-deck mb-3 text-center">
       <div class="card mb-4 shadow-sm">
        <div class="card-header">
          <h4 class="my-0 font-weight-normal">Vous pouvez maintenant crée votre profil !</h4>
        </div>
        <div class="card-body">
          <p>En cliquant sur le lien ci-dessous, vous allez créer une carte qui sera visible de tous les autres utilisateurs, vous pourrez donc être contacté ou contacter vie Meet a Mate ! </p>
          <%= link_to "Crée une nouvelle carte !", new_post_path, class: "btn btn-lg btn-block btn-primary" %>
        </div>
      </div>
    </div>






      <div class="card-deck mb-3 text-center">
        <div class="card mb-4 shadow-sm">
            <h1 class="card-title pricing-card-title">Voici vos futures mates !</h1>
          </div>
      </div>

      <div class="row row-cols-1 row-cols-md-2 justify-content-center ">
        <% @posts.each do |post| %>
            <div class="col-sm-6 card-deck mb-3 text-center">
              <div class="card mb-4 shadow-sm" style="height: 68vh;">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal"><%= post.game %></h4>
                </div>
                  <img src="<%= post.image %>" class="card-img-top img-post" style="max-height: 16em;">
                  <div class="card-body">
                    <td><%= post.surname %></td>
                    <td><%= post.name %></td>
                    <br>
                    <td><%= post.discord %></td>
                    <td><%= post.Pseudo %></td>
                    <br>
                    <td><%= post.others %></td>
                  </div>
               <%= link_to "Modifié", edit_post_path(post), class: "btn btn-lg btn-block btn-secondary" %> 
              </div>
            </div>
        <% end %>
      </div>



    



  </div>

<% else %>

  <div class="container row">
  <div class="col-sm-6 card-deck mb-3 text-center">
    <div class="card mb-4 shadow-sm" style="height: 68vh;">
      <div class="card-header">
          <h4 class="my-0 font-weight-normal">C’est gratuit !</h4>
      </div>
        <img class="card-img-top" src="https://cdn.discordapp.com/attachments/450054113695236097/844620332559761438/katabaka.png" alt="Card image cap" style="weight: 1vh;">
      <div class="card-body">
        <h1 class="card-title pricing-card-title">Trouver le mate parfait !</h1>
        <p class="card-text"><p>Sur Meet a Mate vous pouvez créer votre carte de profil publique.
          Trouvez de nouveau mate, devenez ami et jouez ensemble.
          En fonction des informations que vous donnerez, vous serez sans doute contacté !
          Et à l'inverse n'hésitez pas à contacter les joueurs qui vous intéressent !</p></p>
      </div>
    </div>
  </div>


  <div class="col-sm-6 card-deck mb-3 text-center">
    <div class="card mb-4 shadow-sm" style="height: 68vh;">
      <div class="card-header">
          <h4 class="my-0 font-weight-normal">Inscrivez-vous !</h4>
      </div>
      <img class="card-img-top" src="https://loltracker.com/images/easyblog_images/2638/b2ap3_thumbnail_league_of_legends_fan_art___tahm_kench_retreat___by_benlo-d9ki3br.jpg" alt="Card image cap">
      <div class="card-body">
          <p class="align-middle card-text">Inscrivez-vous en cliquant sur le bouton ci dessous</p>
          <%= link_to "Sign up now", new_account_registration_path, class: "btn btn-lg btn-block btn-info" %>
      </div>
    </div>
  </div>
</div>

<% end %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @post.name %>
</p>

<p>
  <strong>Surname:</strong>
  <%= @post.surname %>
</p>

<p>
  <strong>Discord:</strong>
  <%= @post.discord %>
</p>

<p>
  <strong>Pseudo:</strong>
  <%= @post.Pseudo %>
</p>

<p>
  <strong>Game:</strong>
  <%= @post.game %>
</p>

<p>
  <strong>Others:</strong>
  <%= @post.others %>
</p>

<p>
  <strong>Image:</strong>
  <%= @post.image %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>